/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlarmEditDialog: typeof import('./../pages/config/components/todo/components/AlarmEditDialog.vue')['default']
    AppMain: typeof import('./../layout/components/AppMain.vue')['default']
    Category: typeof import('./../pages/config/components/category/index.vue')['default']
    CategoryItem: typeof import('./../components/CategoryItem/index.vue')['default']
    CodeMirrorEditor: typeof import('./../components/CodeMirrorEditor/index.vue')['default']
    Content: typeof import('./../pages/config/components/category/components/content/index.vue')['default']
    ContentItem: typeof import('./../components/ContentItem/index.vue')['default']
    ContentList: typeof import('./../pages/config/components/category/components/contentList/index.vue')['default']
    ContextMenu: typeof import('./../components/ContextMenu/index.vue')['default']
    CustomButton: typeof import('./../components/UI/CustomButton.vue')['default']
    CustomSwitch: typeof import('./../components/UI/CustomSwitch.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    General: typeof import('./../components/SettingsContent/components/General/index.vue')['default']
    Manger: typeof import('./../components/SettingsContent/components/Manger/index.vue')['default']
    QuickNav: typeof import('./../components/QuickNav/index.vue')['default']
    Result: typeof import('./../pages/search/components/Result.vue')['default']
    Retrieve: typeof import('./../pages/config/components/retrieve/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SegmentedToggle: typeof import('./../components/SegmentedToggle/index.vue')['default']
    Settings: typeof import('./../pages/config/components/category/components/settings/index.vue')['default']
    SettingsContent: typeof import('./../components/SettingsContent/index.vue')['default']
    Shortcut: typeof import('./../components/SettingsContent/components/Shortcut/index.vue')['default']
    Splitter: typeof import('./../components/Splitter/index.vue')['default']
    Summarize: typeof import('./../pages/config/components/summarize/index.vue')['default']
    Titlebar: typeof import('./../layout/components/Titlebar.vue')['default']
    Todo: typeof import('./../pages/config/components/todo/index.vue')['default']
  }
}
