const WINDOWS_ABSOLUTE_PATH = /^[a-zA-Z]:[\\/]/;
const WINDOWS_DRIVE_URL_PATH = /^\/[a-zA-Z]:[\\/]/;

function decodePath(value: string): string {
  try {
    return decodeURIComponent(value);
  } catch {
    return value;
  }
}

function normalizeWindowsPath(value: string): string {
  return value.replace(/\//g, '\\');
}

function isAbsoluteFilePath(value: string): boolean {
  return WINDOWS_ABSOLUTE_PATH.test(value) || value.startsWith('\\\\');
}

/**
 * Extract the local file path generated by Tauri's convertFileSrc.
 * Tauri can use either asset://localhost or http(s)://asset.localhost,
 * depending on the runtime configuration.
 */
export function localPathFromImageSrc(
  src: string | null | undefined
): string | null {
  const value = src?.trim();
  if (!value) return null;

  const decodedValue = decodePath(value);
  if (isAbsoluteFilePath(decodedValue))
    return normalizeWindowsPath(decodedValue);

  try {
    const url = new URL(value);
    const isTauriAssetUrl =
      url.protocol === 'asset:' || url.hostname === 'asset.localhost';
    if (!isTauriAssetUrl && url.protocol !== 'file:') return null;

    let path = decodePath(url.pathname);
    if (WINDOWS_DRIVE_URL_PATH.test(path)) path = path.slice(1);
    path = normalizeWindowsPath(path);
    return isAbsoluteFilePath(path) ? path : null;
  } catch {
    return null;
  }
}

/** Resolve an editor image to an absolute Windows file path. */
export function resolveImageFilePath(
  renderedSrc: string | null | undefined,
  originalPath: string | null | undefined,
  workspaceRoot: string | null | undefined
): string | null {
  const renderedPath = localPathFromImageSrc(renderedSrc);
  if (renderedPath) return renderedPath;

  const decodedOriginalPath = decodePath(originalPath?.trim() || '');
  if (!decodedOriginalPath) return null;
  if (isAbsoluteFilePath(decodedOriginalPath)) {
    return normalizeWindowsPath(decodedOriginalPath);
  }

  const root = workspaceRoot?.trim().replace(/[\\/]+$/, '');
  if (!root) return null;

  // Attachment markdown historically stores both "assets/..." and
  // "../assets/...". Both forms are rooted at the configured workspace.
  const workspaceRelativePath = decodedOriginalPath
    .replace(/^(?:\.\.?[\\/])+/, '')
    .replace(/^[\\/]+/, '');
  if (!workspaceRelativePath) return null;

  return `${normalizeWindowsPath(root)}\\${normalizeWindowsPath(workspaceRelativePath)}`;
}
